# -*- coding: utf-8 -*-
"""islab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sB_3aSJeoW_rRuD9_wfHXQphRWC6X_8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.mixture import GaussianMixture

# Load the Iris dataset
iris = datasets.load_iris()

# Select the first two features (sepal length and sepal width)
X = iris.data[:, :2]

# Create a GMM model with 3 components (assuming there are 3 clusters in the data)
gmm = GaussianMixture(n_components=3, random_state=0)

# Fit the GMM model to the data
gmm.fit(X)

# Predict the cluster assignments for each data point
labels = gmm.predict(X)

# Add the cluster labels to the DataFrame
df = pd.DataFrame(X, columns=["SepalLength", "SepalWidth"])
df["Cluster"] = labels

# Plot the data points with cluster colors
plt.scatter(df["SepalLength"], df["SepalWidth"], c=df["Cluster"], cmap='viridis')
plt.title("Iris Data Clustering with GMM")
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.show()